
server:
  port: 8080
spring:
  datasource:
    name: qiuzhi
    url: jdbc:mysql://localhost:3306/qiuzhi?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.tyt.qiuzhi.dao: debug


#logging



#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true




